[project]
name = "ipin-2025-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flowcean==0.7.0b1",
    "matplotlib>=3.10.6",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
